"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['macos.py']
DATA_FILES = ['src']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={
        'py2app': {"includes": ["os", "hashlib", "sys", "webbrowser", "zipfile"], "iconfile": "icon.icns", "packages": ["PyQt6", "chardet", "requests"]
        }
    },
    setup_requires=['py2app'],
)
